version: '3'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  # mongo-express:
  #   image: mongo-express
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=root
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
  #     - ME_CONFIG_MONGODB_SERVER=mongo
  #   networks:
  #     - app-network
  #   restart: always
    
volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
